### PR TITLE
Replace kaminari by pagy

### LINKED ISSUE #173: Replace kaminari by pagy
Replace `kaminari` gem by `pagy`

### PR DESCRIPTION
**Pull request by MBausson**
Closes #173

### CODE REVIEW

**Comment by nicolas-brousse** [comment]
@B-Rass may needs some alignment/margin changes at least for ChangelogEntries. Otherwise LGTM

**Comment by B-Rass** [comment]
> @B-Rass may needs some alignment/margin changes at least for ChangelogEntries. Otherwise LGTM

Ok done. Do I merge?

**Comment by B-Rass** [comment]
@nicolas-brousse Pagination does not appear on tables on show pages. Is it normal?

**Comment by nicolas-brousse** [comment]
> @nicolas-brousse Pagination does not appear on tables on show pages. Is it normal?

Fixed. I did a fix on servers index too.

**Pull request merged**
