### PR TITLE
Add counter cache

### PR DESCRIPTION
**Pull request by MBausson**

### CODE REVIEW

**Review by B-Rass — CHANGES_REQUESTED** [review]
- [ ] A bug to fix on `Modles`, when sorting by bays count
- [ ] Missing sort on `Rooms - frames count`, `Islets - frames count`, `Bays - servers count`

**Comment by nicolas-brousse** [comment]
> - [ ] A bug to fix on `Modles`, when sorting by bays count
> - [ ] Missing sort on `Rooms - frames count`, `Islets - frames count`, `Bays - servers count` 


- What's the bug on `Modeles`? It's not a `bays_count` fyi, it's on the `bays.id`
- `Frame` has no `belongs_to :modele`, same for islets. So it's not possible to apply counter_cache as we do for others. Same issue for `Servers`

**Comment by B-Rass** [comment]
> > * [ ]  A bug to fix on `Modles`, when sorting by bays count
> > * [ ]  Missing sort on `Rooms - frames count`, `Islets - frames count`, `Bays - servers count`
> 
> 
>     * `Frame` has no `belongs_to :modele`, same for islets. So it's not possible to apply counter_cache as we do for others. Same issue for `Servers`

ok for the missing sorting options

>     * What's the bug on `Modeles`? It's not a `bays_count` fyi, it's on the `bays.id`

Did you tested it?

I have this error `PG::UndefinedColumn: ERROR: column "servers_count" does not exist LINE 1: SELECT "modeles".* FROM "modeles" ORDER BY "servers_count" A... ^ `

**Comment by nicolas-brousse** [comment]
@B-Rass I don't have the issue. Maybe you're DB schema is not up to date

**Review by B-Rass — CHANGES_REQUESTED** [review]

**Comment by B-Rass** [comment]
> @B-Rass I don't have the issue. Maybe you're DB schema is not up to date

Indeed there was an issue in my schema with `servers_count`. I had to comment it, rollback and migrate again

**Review by B-Rass — APPROVED** [review]

**Pull request merged**
